services:
  db:
    image: postgres:16.2-alpine@sha256:22bcd338438a0122475021b3f850546f545559dc4578417933fa98d762e1978f
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: "{{db_password}}"
      POSTGRES_USER: "{{db_username}}"
      POSTGRES_DB: "{{db_username}}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - '{{mount_folder}}/db/:/var/lib/postgresql/data'
  server:
    image: {{username}}/ebook-manager:{{version}}
    restart: on-failure
    ports:
      - "{{port}}:8080"
    environment:
      db-user: "{{db_username}}"
      db-password: "{{db_password}}"
      db-address: db
      db-schema: "{{db_username}}"
      login-salt: "{{login_salt}}"
      admin-username: "{{admin_username}}"
      admin-password: "{{admin_password}}"
    volumes:
      - '{{mount_folder}}/data/:/work/upload'
    depends_on:
      - "db"
