services:
  db:
    image: postgres:15.2-alpine@sha256:07ec36ad2d5ab9250f38c8ef749239b662cf15d03c9ddb7167422edbbdf71156
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: "{{db_password}}"
      POSTGRES_USER: "{{db_username}}"
      POSTGRES_DB: "{{db_username}}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - '{{mount_folder}}/db/:/var/lib/postgresql/data'
  server:
    image: {{username}}/ebook-manager:{{version}}
    restart: on-failure
    ports:
      - "{{port}}:8080"
    environment:
      db-user: "{{db_username}}"
      db-password: "{{db_password}}"
      db-address: db
      db-schema: "{{db_username}}"
      login-salt: "{{login_salt}}"
      admin-username: "{{admin_username}}"
      admin-password: "{{admin_password}}"
    volumes:
      - '{{mount_folder}}/data/:/home/jboss/upload'
    depends_on:
      - "db"
