containers:
  postgres:
    image: postgres
    version: 15.2-alpine

quarkus:
  datasource:
    devservices:
      enabled: true
      image-name: ${containers.postgres.image}:${containers.postgres.version}
    jdbc:
      driver: org.testcontainers.jdbc.ContainerDatabaseDriver
      url: jdbc:tc:postgresql:${containers.postgres.version}:///test