quarkus:
  datasource:
    db-kind: postgresql
    username: ${db-user}
    password: ${db-password}
    jdbc:
      url: jdbc:postgresql://${db-address}/${db-schema}
  http:
    auth:
      basic: true
    limits:
      max-form-attribute-size: 200M
      max-body-size: 200M
  flyway:
    default-schema: public
    clean-at-start: false
    table: SCHEMA_VERSION
    validate-on-migrate: true
    out-of-order: false
    migrate-at-start: true
  container-image:
    builder: jib
  jib:
    base-jvm-image: gcr.io/distroless/java17:nonroot
    base-native-image: afrima/quarkus-base-image:1.0.17@sha256:ca75034d739c5c5c80d2ae1b27dd591a299bbd72cd765759f493f1f72bdca2be

login:
  salt: ${login-salt}
  iteration: ${login-iteration:4}
  admin:
    username: ${admin-username}
    password: ${admin-password}