containers:
  mongodb:
    image: mongo
    version: 7.0.4

quarkus:
  mongodb:
    connection-string: "mongodb://localhost:27017"
    database: test
    devservices:
      port: 27017
      enabled: true
      image-name: ${containers.mongodb.image}:${containers.mongodb.version}