quarkus:
  mongodb:
    database: ebooks
  http:
    auth:
      basic: true
    limits:
      max-form-attribute-size: 200M
      max-body-size: 200M
  container-image:
    builder: jib
  jib:
    base-jvm-image: gcr.io/distroless/java21:nonroot
    base-native-image: afrima/quarkus-base-image:1.1.9@sha256:1ff03c23371f0634698dd4ef4068b3ce521349ed48bc1e813c11d04a3dbc08c3
  native:
    additional-build-args: -march=x86-64-v2
login:
  salt: ${login-salt}
  iteration: ${login-iteration:4}
  admin:
    username: ${admin-username}
    password: ${admin-password}