quarkus:
  datasource:
    devservices:
      enabled: true
      image-name: postgres:15.1@sha256:f4cd32e7a418d9c9ba043e7d561243388202b654c740bcc85ca40b41d9fb4f1e
    jdbc:
      driver: org.testcontainers.jdbc.ContainerDatabaseDriver
      url: jdbc:tc:postgresql:latest:///test