quarkus:
  datasource:
    db-kind: postgresql
    username: ${db-user}
    password: ${db-password}
    jdbc:
      url: jdbc:postgresql://${db-address}/${db-schema}
  http:
    auth:
      basic: true
    limits:
      max-form-attribute-size: 200M
      max-body-size: 200M
  flyway:
    default-schema: public
    clean-at-start: false
    table: SCHEMA_VERSION
    validate-on-migrate: true
    out-of-order: false
    migrate-at-start: true
  container-image:
    builder: jib
  jib:
    base-jvm-image: gcr.io/distroless/java21:nonroot
    base-native-image: afrima/quarkus-base-image:1.1.14@sha256:a9b3bb0b5efc67b4c2d91d10ff7ebd0ef23370ca77b110930e4cc277a2f80d8e
  native:
    additional-build-args: -march=x86-64-v2
login:
  salt: ${login-salt}
  iteration: ${login-iteration:4}
  admin:
    username: ${admin-username}
    password: ${admin-password}